#!/bin/bash

src="models"
dir="policy"

cd models
mkdir -p $dir

# get yangs and omit primitives
files="$(find . -type f \( -name "sonic-*.yang" ! -name "sonic-extension*" ! -name "sonic-common*" ! -name "sonic-show*" \))" 

for file in $files; 
  do 
  pref="$(basename -- $file | sed 's/.yang//g')"
  new="$(basename -- $file | sed 's/.yang/.json/g')"
  pyang -p ./yang -f jsonschema $file | jq ".properties.\"$pref:$pref\".properties" > $dir/$new
done

# make a config_db validator
jq -s "{\"title\": \"config_db\", \"\$schema\": \"http://json-schema.org/2020-12/schema\", \"description\": \"Generated by validator script\", \"type\": \"object\", \"properties\": add }"  $dir/*.json > $dir/config_db.jsonschema

# get jsons to append properties to
jsons="$(find . -type f \( -name "sonic-*.json" \))"

# pull the files
for file in $jsons; 
  do 
  new="$(basename -- $file )"
  cat <<< $(jq -s "{\"\$id\": \"$new\", \"type\": \"object\", \"properties\": add }" $file ) > $file
done
